# Generated by Django 2.2.14 on 2022-03-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
